# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WhatsTheWeather < Formula
  desc ""
  homepage "https://github.com/ciaarraa/whats-the-weather"
  version "1.0.3-alpha"

  on_macos do
    on_intel do
      url "https://github.com/ciaarraa/whats-the-weather/releases/download/v1.0.3-alpha/whats-the-weather_Darwin_x86_64.tar.gz"
      sha256 "b8996f8a8d70a3d93c1da9f16e81b63c6bc58a89caf9ea6d286722851d9391d6"

      def install
        bin.install "whats-the-weather"
      end
    end
    on_arm do
      url "https://github.com/ciaarraa/whats-the-weather/releases/download/v1.0.3-alpha/whats-the-weather_Darwin_arm64.tar.gz"
      sha256 "99e8091f47e6a5878de5fac2d65cdef846c5d81d4900d7b10edb1a1e4585b38d"

      def install
        bin.install "whats-the-weather"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ciaarraa/whats-the-weather/releases/download/v1.0.3-alpha/whats-the-weather_Linux_x86_64.tar.gz"
        sha256 "c17044e9c22b24900bcc18506e77c3cde3d2e43bb8fd32176ed3e25cb7f465bc"

        def install
          bin.install "whats-the-weather"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ciaarraa/whats-the-weather/releases/download/v1.0.3-alpha/whats-the-weather_Linux_arm64.tar.gz"
        sha256 "dd949b7595956489fc0a160b269760000a4aae70b7bc1147cb0ea26bb6e99420"

        def install
          bin.install "whats-the-weather"
        end
      end
    end
  end
end
