# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WhatsTheWeather < Formula
  desc ""
  homepage "https://github.com/ciaarraa/whats-the-weather"
  version "1.0.2-alpha"

  on_macos do
    on_intel do
      url "https://github.com/ciaarraa/whats-the-weather/releases/download/v1.0.2-alpha/whats-the-weather_Darwin_x86_64.tar.gz"
      sha256 "a1aca1ffe49708147233507adb7a4e093643d225af6e38f2c0dbd6d96503aa6c"

      def install
        bin.install "whats-the-weather"
      end
    end
    on_arm do
      url "https://github.com/ciaarraa/whats-the-weather/releases/download/v1.0.2-alpha/whats-the-weather_Darwin_arm64.tar.gz"
      sha256 "d96f897ff342fa8f4c068eac13e0113aa91c815bbf2093f82f9c8df747b02850"

      def install
        bin.install "whats-the-weather"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ciaarraa/whats-the-weather/releases/download/v1.0.2-alpha/whats-the-weather_Linux_x86_64.tar.gz"
        sha256 "347a7852efda72f726c971bf36435b7c7263dc509c5bd0a1d004bcf634f41ac8"

        def install
          bin.install "whats-the-weather"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ciaarraa/whats-the-weather/releases/download/v1.0.2-alpha/whats-the-weather_Linux_arm64.tar.gz"
        sha256 "0499f362f79360a810480ad438fd2c61e1c3431bf3cfbeed6ca73d6cf5589c27"

        def install
          bin.install "whats-the-weather"
        end
      end
    end
  end
end
